### ISSUE TITLE
'SXT/Parts/Utility/floats/airboatmidsmall' as model does not exist

### ISSUE THREAD

**Issue by RealKolago** [Signatum/SXT#10]
PartLoader: Compiling Part 'SXT/Parts/Utility/floats/partMidSmall/SXTfloatMidSmall'
PartCompiler: Cannot clone model 'SXT/Parts/Utility/floats/airboatmidsmall' as model does not exist
PartCompiler: Model was not compiled correctly
PartCompiler: Cannot compile model
PartCompiler: Cannot compile part

**Comment by Signatum** [comment]
Ah, those are old parts that got formally retired when I re-did the models. I hadn't wanted to delete the config files in case anyone had any old craft with them on. Having them not loading shouldn't have any negative effects, but given that they'd been disabled for a few versions before that it's probably safe to delete them now.

The current configs in Utility/floats/

part.cfg - 'LF-01A Sea-Float End' [In use]
partMid.cfg - 'LF-01B Sea-Float Midsection' [In use]
partMidSmall.cfg - 'Small Floats [Mid]' [Retired]
partOutboard.cfg - 'LF-01B Sea-Float Outrigger' [In use]
partSmall.cfg - 'Small Floats [Front]' [Retired]
