### ISSUE TITLE
CKAN Error

### ISSUE THREAD

**Issue by polkinghornbd** [Signatum/SXT#17]
Whenever I try to update my STX to v25.1, I get this message.

Failed to download "https://github.com/Signatum/SXT/releases/download/v25.1/SXT25pre.zip" - error: The request was aborted: The connection was closed unexpectedly.

Do you know what could be causing this?

Thanks

**Comment by NathanKell** [comment]
That is something to ask the CKAN folks, I think. Looks like it's targeting an old release rather than the current release.
