### ISSUE TITLE
Nozzle-extension AJ10

### ISSUE THREAD

**Issue by NathanKell** [Signatum/SXT#5]
If you do decide to make one, can you name it SXTAJ10Mid ? Then I can seamlessly remove the clone I'm currently using. :)

**Comment by Signatum** [comment]
http://imgur.com/a/EFFZf 

Pushed to experimental branch currently. Longer tubes at top & fixed colliders for both, version with longer nozzle called SXTAJ10Mid (note, category is set to -1 and TechRequired and Entry Cost are tabbed out).

**Comment by NathanKell** [comment]
That looks amazing! Thanks so much! :)
Can't wait to try it out.

**Comment by NathanKell** [comment]
(I won't be able to try KSP until tomorrow evening; I realize it's on git. :) )

**Comment by NathanKell** [comment]
Closing due to awesomeness. :)
