### ISSUE TITLE
CKAN and building release zips

### ISSUE THREAD

**Issue by NathanKell** [Signatum/SXT#7]
CKAN does not yet support grabbing a 'source' zip from a github release. Thus I have taken the liberty of building a 22.3 release zip so CKAN will index (it hasn't indexed in a while). The alternative is switching CKAN back to grabbing from the SXT entry on KerbalStuff, so if you plan to keep that updated (I noticed it was on 22.2 not 22.3) we should swap the CKAN metadata back to pulling from KerbalStuff instead? (Unless you do want to upload release zips to git, or @pjf and the gang add support for source zips.)

**Comment by Signatum** [comment]
I was thinking about keeping the GitHub updated for people who regularly check the thread (providing I actually update the thread, last night it was essentially a case of 'good enough, I'm going to bed'), and then updating Kerbalstuff for CKAN every weekend. If I've pushed a few smaller patches through the week, they can then just download those collectively.

It also means if I've broken something and haven't realised, there's a bit of time to correct it before I put it out to everyone (or I could just test things more thoroughly, but where's the fun in that).

Though I'm not actually sure how CKAN handles updates (haven't actually used it yet). Are the updates automatic, or does it just notify you if there's an update available?

**Comment by pjf** [comment]
> Though I'm not actually sure how CKAN handles updates (haven't actually used it yet). Are the updates automatic, or does it just notify you if there's an update available?

The user gets an upgrade box. If they tick it and apply changes, then they get the upgrade. :)

If the github releases are identical to what's in the code repository, then I'm pretty sure we can get [travis](https://travis-ci.org/) to build and upload assets automatically (which also means one can have a release script which strips out extraneous files like `.gitignore`, and so on).

**Comment by NathanKell** [comment]
@Signatum right now the CKAN netkan (the thing that autogenerates metadata) points to github. It can be changed to KerbalStuff, but as @pjf says probably the easiest solution for you is to add a build script, and then whenever you make a release, the script will automatically build a release zip for you, which you can then upload to Kerbalstuff (or even have travis do that automatically maybe?).

So the options are, right now:
1. Switch netkan over to point at KerbalStuff, continue doing what you're doing, CKAN users will only get updates when they pop up on KerbalStuff.
2a. Leave netkan as it is, manually add release zips to github, github remains the location CKAN points towards.
2b. Leave netkan as it is, Add a travis script to autobuild the releases, whenever you hit 'make release' and save it travis will build a release zip for you which you can (or maybe travis can) upload to KerbalStuff, github remains the location CKAN points toward.

2a is what is currently the case.

**Comment by Signatum** [comment]
Opps, forgot about this thread. Yes, the github releases should be identical to what's in the repository (minus the .git stuff), so I'll have to have a look at scripts/travis properly.

Also, I've had a few people having problems with CKAN, SXT and Firespitter (I've already moved the Sounds folder into SXT after reading about that). Is there a way to have FS as a dependency for SXT? At the moment the game won't load without it (one of the engines uses FScoolant) and half the parts are set to not show up if someone deletes FS.

**Comment by Signatum** [comment]
CKAN dependencies sorted now.
